# Generated by Django 5.1.7 on 2025-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Education', 'Education'), ('Other', 'Other')], max_length=50),
        ),
    ]
