# Generated by Django 5.1.7 on 2025-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Other Income', 'Other Income'), ('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Education', 'Education'), ('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Insurance', 'Insurance'), ('Other Expense', 'Other Expense')], max_length=50),
        ),
    ]
