# Generated by Django 5.1.7 on 2025-03-31 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_recurrence_recurringtransaction_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='daily_budget',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='weekly_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
