# Generated by Django 5.1.7 on 2025-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_daily_budget_budget_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
