# Generated by Django 5.1.7 on 2025-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_category_recurringtransaction_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='next_due_date',
            new_name='next_occurrence',
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10),
        ),
    ]
