# Generated by Django 5.1.7 on 2025-04-02 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_name_recurringtransaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='period',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='budget',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='weekly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
