# Generated by Django 5.1.7 on 2025-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_budget_amount_remove_budget_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='weekly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
