# Generated by Django 5.1.7 on 2025-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_budget_conversion_rate_budget_original_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='daily_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='weekly_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='converted_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='converted_monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='converted_weekly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='original_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='original_monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='original_weekly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
