# Generated by Django 5.1.7 on 2025-04-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_budget_daily_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='conversion_rate',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='converted_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='converted_monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='converted_weekly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='original_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='original_monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='original_weekly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Other Income', 'Other Income'), ('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Education', 'Education'), ('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Insurance', 'Insurance'), ('Other Expense', 'Other Expense')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
