# Generated by Django 5.1.7 on 2025-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_budget_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='original_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
