# Generated by Django 5.1.7 on 2025-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_budget_original_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
