# Generated by Django 5.1.7 on 2025-04-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_budget_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='original_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
