# Generated by Django 5.1.7 on 2025-04-03 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_recurringtransaction_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='last_updated',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='original_currency',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='converted_daily_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='converted_monthly_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='converted_weekly_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='original_daily_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='original_monthly_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='original_weekly_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
