# Generated by Django 5.1.7 on 2025-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_budget_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
