# Generated by Django 5.1.7 on 2025-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_budget_currency_alter_budget_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'period')},
        ),
    ]
