# Generated by Django 5.1.7 on 2025-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_budget_currency_alter_budget_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='period',
            new_name='budget_type',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='updated_at',
        ),
    ]
