# Generated by Django 5.1.7 on 2025-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_budget_original_amount_budget_original_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='original_currency',
            field=models.CharField(max_length=3),
        ),
    ]
