# Generated by Django 5.1.7 on 2025-04-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_usd_amount_budget_amount_usd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
