# Generated by Django 5.1.7 on 2025-04-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_customuser_theme_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='theme_preference',
        ),
    ]
